apiVersion: v1
kind: Pod
metadata:
  name: vfio-consumer
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sleep", "123"]
    resources:
      limits:
        devices.netronome.io/vfio: 1
